version: '3.8'
services:
  api:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  client:
    build:
      context: ../live-reader-client
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - api
